In [130]:
import easyocr, cv2, os
import numpy as np

In [59]:
path = "./dataset/scientific_publication/"
imgList = os.listdir(path)
img = cv2.imread(path + imgList[1])
cv2.imshow("원본", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [60]:
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow("흑백", gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [70]:
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
gray = cv2.GaussianBlur(gray, (3, 3), 0)
cv2.imshow("흑백", gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [74]:
# Morphological Transformation
kernel  = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (3, 3))
grad = cv2.morphologyEx(gray, cv2.MORPH_GRADIENT, kernel)
_, bw = cv2.threshold(grad, 0.0, 255.0, cv2.THRESH_BINARY | cv2.THRESH_OTSU)
kernel2 = cv2.getStructuringElement(cv2.MORPH_RECT, (20,1))
connected = cv2.morphologyEx(bw, cv2.MORPH_CLOSE, kernel2)

contours, hierarchy = cv2.findContours(connected.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
mask = np.zeros(bw.shape, dtype=np.uint8)
rgb = img.copy()
for idx in range(len(contours)):
    x, y, w, h = cv2.boundingRect(contours[idx])
    mask[y:y+h, x:x+w] = 0
    cv2.drawContours(mask, contours, idx, (255, 255, 255), -1)
    r = float(cv2.countNonZero(mask[y:y+h, x:x+w])) / (w*h)
    if r > 0.35 and w > 8 and h > 8 :
        cv2.rectangle(rgb, (x,y), (x+w, y+h), (0, 255, 0), 2)

cv2.imshow("원본", img)
cv2.imshow("흑백", gray)
cv2.imshow("변환", grad)
cv2.imshow("close", connected)
cv2.imshow("윤곽", rgb)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [56]:
import os
os.listdir('./dataset/scientific_publication/')

['doc_000016.png',
 'doc_000045.png',
 'doc_000050.png',
 'doc_000061.png',
 'doc_000089.png',
 'doc_000121.png',
 'doc_000128.png',
 'doc_000130.png',
 'doc_000171.png',
 'doc_000228.png',
 'doc_000235.png',
 'doc_000240.png',
 'doc_000250.png',
 'doc_000285.png',
 'doc_000298.png',
 'doc_000309.png',
 'doc_000311.png',
 'doc_000334.png',
 'doc_000345.png',
 'doc_000349.png',
 'doc_000392.png',
 'doc_000429.png',
 'doc_000437.png',
 'doc_000438.png',
 'doc_000445.png',
 'doc_000451.png',
 'doc_000453.png',
 'doc_000480.png',
 'doc_000498.png',
 'doc_000509.png',
 'doc_000513.png',
 'doc_000515.png',
 'doc_000522.png',
 'doc_000530.png',
 'doc_000534.png',
 'doc_000584.png',
 'doc_000594.png',
 'doc_000615.png',
 'doc_000617.png',
 'doc_000697.png',
 'doc_000698.png',
 'doc_000741.png',
 'doc_000756.png',
 'doc_000766.png',
 'doc_000767.png',
 'doc_000769.png',
 'doc_000779.png',
 'doc_000785.png',
 'doc_000821.png',
 'doc_000832.png',
 'doc_000845.png',
 'doc_000864.png',
 'doc_000891

In [131]:
path = "./dataset/scientific_publication/"
imgList = os.listdir(path)
for idx in range(5, 10) : 
    img = cv2.imread(path+imgList[idx])
    # 흑백처리 및 노이즈 제거
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    gray = cv2.GaussianBlur(gray, (3, 3), 0)
    # Morphology Transform - 1차
    kernel  = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (3, 3))
    grad = cv2.morphologyEx(gray, cv2.MORPH_GRADIENT, kernel)
    # Morphology Transform - 2차
    _, bw = cv2.threshold(grad, 0.0, 255.0, cv2.THRESH_BINARY | cv2.THRESH_OTSU)
    kernel2 = cv2.getStructuringElement(cv2.MORPH_RECT, (20,1))
    connected = cv2.morphologyEx(bw, cv2.MORPH_CLOSE, kernel2)
    # contour 찾기
    contours, hierarchy = cv2.findContours(connected.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    mask = np.zeros(bw.shape, dtype=np.uint8)
    rgb = img.copy()
    for idx in range(len(contours)):
        x, y, w, h = cv2.boundingRect(contours[idx])
        mask[y:y+h, x:x+w] = 0
        cv2.drawContours(mask, contours, idx, (255, 255, 255), -1)
        r = float(cv2.countNonZero(mask[y:y+h, x:x+w])) / (w*h)
        if r > 0.35 and w > 8 and h > 8 :
            cv2.rectangle(rgb, (x,y), (x+w, y+h), (0, 255, 0), 2)
    cv2.imshow("윤곽"+str(idx), rgb)
cv2.waitKey(0)
cv2.destroyAllWindows()





In [137]:
def getTextBox(img) : 
    contourList = []
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    gray = cv2.GaussianBlur(gray, (3, 3), 0)
    # Morphology Transform - 1차
    kernel  = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (3, 3))
    grad = cv2.morphologyEx(gray, cv2.MORPH_GRADIENT, kernel)
    # Morphology Transform - 2차
    _, bw = cv2.threshold(grad, 0.0, 255.0, cv2.THRESH_BINARY | cv2.THRESH_OTSU)
    kernel2 = cv2.getStructuringElement(cv2.MORPH_RECT, (20,1))
    connected = cv2.morphologyEx(bw, cv2.MORPH_CLOSE, kernel2)
    # contour 찾기
    contours, hierarchy = cv2.findContours(connected.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    mask = np.zeros(bw.shape, dtype=np.uint8)
    rgb = img.copy()
    for idx in range(len(contours)):
        x, y, w, h = cv2.boundingRect(contours[idx])
        mask[y:y+h, x:x+w] = 0
        cv2.drawContours(mask, contours, idx, (255, 255, 255), -1)
        r = float(cv2.countNonZero(mask[y:y+h, x:x+w])) / (w*h)
        if r > 0.35 and w > 8 and h > 8 :
            cv2.rectangle(rgb, (x,y), (x+w, y+h), (0, 255, 0), 2)
            contourList.append(contours[idx])
    # cv2.imshow("result", rgb)
    return (rgb, contourList)
img = cv2.imread(path+imgList[1])
result = getTextBox(img)
cv2.imshow("result", result[0])
cv2.waitKey(0)
cv2.destroyAllWindows()


In [145]:
path = "./dataset/scientific_publication/"
imgList = os.listdir(path)
for idx in range(5, 10) : 
    img = cv2.imread(path+imgList[idx])
    result = getTextBox(img)
    cv2.imshow("result"+str(idx), result[0])
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[ 65 935]]

 [[ 64 936]]

 [[ 63 936]]

 [[ 62 937]]

 [[ 62 938]]

 [[ 62 939]]

 [[ 63 940]]

 [[ 63 941]]

 [[ 63 942]]

 [[ 63 943]]

 [[ 64 944]]

 [[ 65 945]]

 [[ 66 945]]

 [[ 67 945]]

 [[ 68 945]]

 [[ 69 945]]

 [[ 70 945]]

 [[ 71 945]]

 [[ 72 945]]

 [[ 73 945]]

 [[ 74 945]]

 [[ 75 945]]

 [[ 76 945]]

 [[ 77 945]]

 [[ 78 945]]

 [[ 79 945]]

 [[ 80 945]]

 [[ 81 945]]

 [[ 82 945]]

 [[ 83 944]]

 [[ 84 943]]

 [[ 85 942]]

 [[ 85 941]]

 [[ 85 940]]

 [[ 84 939]]

 [[ 84 938]]

 [[ 84 937]]

 [[ 84 936]]

 [[ 83 935]]

 [[ 82 935]]

 [[ 81 935]]

 [[ 80 935]]

 [[ 79 935]]

 [[ 78 935]]

 [[ 77 935]]

 [[ 76 935]]

 [[ 75 935]]

 [[ 74 935]]

 [[ 73 935]]

 [[ 72 935]]

 [[ 71 935]]

 [[ 70 935]]

 [[ 69 935]]

 [[ 68 935]]

 [[ 67 935]]

 [[ 66 935]]]
[[[346 922]]

 [[345 923]]

 [[344 923]]

 [[343 923]]

 [[342 923]]

 [[341 923]]

 [[340 923]]

 [[339 923]]

 [[338 923]]

 [[337 923]]

 [[336 924]]

 [[336 925]]

 [[337 926]]

 [[338 926]]

 [[339 926]]

 [[340

In [143]:
img = cv2.imread('./sample1.jpg')
img.shape #height, width

def imgResizeByHeight(img, height) :
    realH = img.shape[0]
    realW = img.shape[1]
    ratio = height/realH
    width = int(realW * ratio)
    return cv2.resize(img, (width, height))

img_ = imgResizeByHeight(img, 900)
result = getTextBox(img_)
cv2.imshow("result", result[0])
result_ = getTextBox(result[0])
cv2.imshow("result_", result_[0])
# cv2.imshow("result", imgResizeByHeight(img, 900))
cv2.waitKey(0)
cv2.destroyAllWindows()
